[server]
udp_bind_address = "0.0.0.0:8080"
public_udp_address = "45.79.162.24:8080"
http_bind_address = "0.0.0.0:8081"

[relay]
auto_shutdown = false

[registry]
registry_address = "https://nodetunnel-db.fly.dev"