services:
  relay:
    image: ghcr.io/nodetunnel/relay-server:latest
    ports:
      - "8081:8081"
      - "8080:8080/udp"
    environment:
      - UDP_BIND_ADDRESS=${UDP_BIND_ADDRESS}
      - ALLOWED_VERSIONS=${ALLOWED_VERSIONS}
      - WHITELIST=${WHITELIST}
      - REMOTE_WHITELIST_ENDPOINT=${REMOTE_WHITELIST_ENDPOINT}
      - REMOTE_WHITELIST_TOKEN=${REMOTE_WHITELIST_TOKEN}
      - RELAY_ID=${RELAY_ID}
      - MAX_CLIENT_BYTES_PER_SEC=${MAX_CLIENT_BYTES_PER_SEC:-65536}
      - MAX_GLOBAL_BYTES_PER_SEC=${MAX_GLOBAL_BYTES_PER_SEC:-2000000}
      - MAX_DAILY_BYTES=${MAX_DAILY_BYTES:-5000000000}
      - MAX_DAILY_CONTROL_BYTES=${MAX_DAILY_CONTROL_BYTES:-250000000}
      - TRAFFIC_INTERVAL_MS=${TRAFFIC_INTERVAL_MS:-250}
      - MAX_SESSION_BYTES=${MAX_SESSION_BYTES:-2000000000}
      - MAX_SESSION_SECS=${MAX_SESSION_SECS:-14400}