services:
  relay:
    image: ghcr.io/nodetunnel/relay-server:latest
    ports:
      - "8080:8080/udp"
    environment:
      - UDP_BIND_ADDRESS=${UDP_BIND_ADDRESS}
      - ALLOWED_VERSIONS=${ALLOWED_VERSIONS}
      - WHITELIST=${WHITELIST}
      - REMOTE_WHITELIST_ENDPOINT=${REMOTE_WHITELIST_ENDPOINT}
      - REMOTE_WHITELIST_TOKEN=${REMOTE_WHITELIST_TOKEN}
      - RELAY_ID=${RELAY_ID}
      - SESSION_TIMEOUT_SECS=${SESSION_TIMEOUT_SECS:-5}
